# Uncomment the next line to define a global platform for your project
# platform :ios, ’10.0’

target 'weatherDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'MBProgressHUD', '~> 1.0.0'
pod 'ShareSDK3'
pod 'MOBFoundation'

pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'


  # Pods for weatherDemo

  target 'weatherDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weatherDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
